# Workflow to execute when a new version is released
name: Release

on:
  release:
  
  # Used for testing and manual execution
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag Ref'
        required: true

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      
    env:
      LIB_PROJ: nugettestrepo_delete_me_soon/nugettestrepo_delete_me_soon.csproj
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.events.inputs.tag }}
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        
    - name: Show .NET info
      run: dotnet --info

    - name: Restore dependencies
      run: dotnet restore

    - name: Build library (Debug)
      run: dotnet build --no-restore -c debug ${{ env.LIB_PROJ }}
      
    - name: Build library (Release)
      run: dotnet build --no-restore -c release ${{ env.LIB_PROJ }}

    - name: Publish the package to nuget.org
      run: dotnet nuget push  ${{ env.LIB_PROJ }}/bin/Release/*.nupkg --api-key $NUGET_AUTH_TOKEN --source https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_KEY }}
