name: published to nuget

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v4

      - name: Set Version Variable
        if: ${{ github.ref_type == 'tag' }}
        env:
          TAG: ${{ github.ref_name }}
        run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build library (Release)
        run: dotnet build --no-restore /p:Version=$VERSION -c release nugettestrepo_delete_me_soon/nugettestrepo_delete_me_soon.csproj

      - name: Create nuget package
        run: dotnet pack /p:PackageVersion=$VERSION -c release --include-symbols

      - name: Publish the package to nuget.org
        run: dotnet nuget push nugettestrepo_delete_me_soon/bin/Release/*.nupkg --api-key $NUGET_AUTH_TOKEN --source https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_KEY }}